import Header from "../components/Header/Header";
import Head from "next/head";
import SelectFormOrSuccess from "../components/Form/SelectFormOrSuccess";

const Contact = () => {
  return (
    <div>
      <Head>
        <title>Contact Us!</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <div className="bg-yellow-400 min-h-screen flex justify-center items-center pt-16">
        <div className="bg-yellow-200 w-full h-3/4 p-8">
          <SelectFormOrSuccess />
        </div>
      </div>
    </div>
  );
};

export default Contact;
