import Head from "next/dist/next-server/lib/head"

export default function Mexico () {
    return (
        <div>
            <Head>
                <title>Mexico</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div>
                <p>Hello Mexico</p>
            </div>

        </div>
    )
}